name: CI Pipeline
run-name: CI 🚀
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Installing Devbox ⚙️
        uses: jetpack-io/devbox-install-action@v0.8.0
      - name: Install all dependencies 📦
        run: devbox run install
      - name: 🧹 Linting & Formatting
        run: devbox run lint && devbox run format
      - name: 🧪 Running Tests
        run: devbox run test
      - run: echo "🍏 This job's status is ${{ job.status }}."
